-- =====================================================
-- PASSWORD FIX SCRIPT
-- =====================================================
-- Use this if you need to reset user passwords
-- Password: password123 (hash generated by Laravel)
-- =====================================================

-- Update all users with the correct password hash
UPDATE users SET 
    password = '$2y$10$fhosSdBQshu318lUmDFzquJhNoht0NCMy/enZxHaCUVabLZzrnBkO'
WHERE id IN (1,2,3,4,5,6,7);

-- Verify the update
SELECT 
    id,
    name,
    email,
    'password123' as password,
    'All users can now login with password123' as status
FROM users
WHERE id IN (1,2,3,4,5,6,7)
ORDER BY id;